services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: devsecops-backend

    env_file:
      - ./backend/.env.docker

    expose:
      - "5000"

    networks:
      - devsecops-network

    volumes:
      - devsecops-uploads:/app/uploads

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:5000/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: devsecops-frontend

    ports:
      - "8080:80"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - devsecops-network

    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v3.14.0

    container_name: devsecops-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    networks:
      - devsecops-network

    restart: unless-stopped


  node-exporter:
    image: prom/node-exporter:v1.12.1

    container_name: devsecops-node-exporter

    ports:
      - "9100:9100"

    networks:
      - devsecops-network

    restart: unless-stopped


  grafana:
    image: grafana/grafana:13.2.0

    container_name: devsecops-grafana

    ports:
      - "3000:3000"

    env_file:
      - ./monitoring/grafana/.env

    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

    networks:
      - devsecops-network

    restart: unless-stopped

networks:
  devsecops-network:
    external: true


volumes:
  devsecops-uploads:
    external: true

  prometheus-data:

  grafana-data:
