name: DevSecOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm audit --audit-level=high


  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build


  trivy-filesystem:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"


  docker:
    name: Docker Build and Security Scan
    runs-on: ubuntu-latest

    needs:
      - backend
      - frontend
      - trivy-filesystem

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create temporary environment files for CI
        run: |
          touch backend/.env.docker
          touch monitoring/grafana/.env

      - name: Validate Docker Compose configuration
        run: docker compose config

      - name: Build Docker images
        run: docker compose build

      - name: Scan backend Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-social-app-backend:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"

      - name: Scan frontend Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-social-app-frontend:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
